### ISSUE TITLE
bunch of view bugs

### ISSUE THREAD

**Issue by MohammadKh** [babakhani/pwt.datepicker#164]
1. in time picker when you disable for example second, the second divider still exists.
2. the date/time picker does not respond to window events & is not a sticky plugin to the corresponding element(ex. on browser windows resize=>like jQuery UI datepicker).
3.  there is no item in option to set custom class.
4.  there is no item in option to set default/initial date/time value.

**Comment by babakhani** [comment]
@MohammadKh 

1. fixed in version  1.0.0
2. I will fix it in next minor version
3. After version 0.5.0 persian-datepicker support `template` config that make you do every thing you want with datepicker html. See interactive [Example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html)
4. Yes there is, [Example](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/#initialvaluetype)

```html
input sample
<input value="2025/3/12"   />

inline example
<div class="leapyear-algorithmic" data-date="2025/3/12" ></div>
```
