### ISSUE TITLE
setDate() bug

### ISSUE THREAD

**Issue by hatamiarash7** [babakhani/pwt.datepicker#297]
<p dir="rtl">
سلام. این تابع مقدار صحیحی رو نشون نمیده. مثالی که شما توی مستندات استفاده کردید مقدار 1382276091100 هست که اگر به تاریخ واقعی تبدیلش کنید میبینید که کلا اشتباهه.
</p>
<p dir="rtl">
گرچه در حال حاضر با استفاده از همین مقدار که تو صفحه آموزش خود کتابخانه هست ، کمی اعداد و ارقام رو جابجا و مقایسه کردم.
</p>
<p dir="rtl">
مقداری که کتابخانه صحیح نشون بده با این فرمول به دست میاد :
</p>

```js
setDate(unix * 1000 + 48891100)
```
<p dir="rtl">
لطفا ایرادش رو برطرف کنید. کتابخانه کاربردی و خوبی هست.
</p>
<p dir="rtl">
تشکر
</p>

**Comment by keyone2693** [comment]
خدا امواتتو بیامرزه

**Comment by babakhani** [comment]
@hatamiarash7 setDate accept unix timestamp like Javasceript `Date.now()` returns to us 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now
`
The static Date.now() method returns the number of milliseconds elapsed since January 1, 1970 00:00:00 UTC.
`

as you can see it works fine in this example https://jsfiddle.net/babareza/u1pm8j7w/
