### ISSUE TITLE
setDate function issue

### ISSUE THREAD

**Issue by hamedkeivan** [babakhani/pwt.datepicker#337]
زمانی که از تابع ست دیت استفاده میشود این خطا را میدهد
Uncaught TypeError: Cannot read property 'setDate' of undefined
کدی هم که نوشتم خیلی ساده س نمیدونم چرا کار نمیکنه
 document.getElementById(t + "date_from").persianDatepicker().setDate(1382276091100);
هر مدلی هم مینویسم خطا میدهد

**Comment by hadimajidi** [comment]
in addition of  hamedkeivan when the function setDate is in using, goes back to the default setting and  observer option stops working and the format returns to LLLL

**Comment by ehsanakhlaghi** [comment]
Hi ,Could you please help me about setDate option for Persian calendar, I don`t know how to Use it in my module,for mini calendar.

**Comment by hadimajidi** [comment]
> Hi ,Could you please help me about setDate option for Persian calendar, I don`t know how to Use it in my module, for a mini calendar.

you can set it by 
document.getElementById(t + "date_from").persianDatepicker().setDate(xxxx);
as far as remember the xxx was a normal javascript date. But the problem is when you execute this command all settings return to the default values and it shows the LLLL or L values with all parameters such as minutes and seconds that may be redundant. I am looking forward to hearing some additional information from the writer.
there is another solution if your parameter comes directly from the server by importing directly to the input HTML parameter.

**Comment by babakhani** [comment]
Hi, I created an example on jsfiddle and as you can see there is not any problem with setDate method, could you explain more? which version do you use? 
Please create a jsfiffle by forking my exmaple.  
https://jsfiddle.net/babareza/L2qd2q7k/

**Comment by hadimajidi** [comment]
> Hi, I created an example on jsfiddle and as you can see there is not any problem with setDate method, could you explain more? which version do you use?
> Please create a jsfiffle by forking my exmaple.
> https://jsfiddle.net/babareza/L2qd2q7k/

thx but the problem is if you use this function you should redefine all parameters for that. If you defined that before with mintime max time and the other parameter you would redefine all them again. The function does not keep the previous settings. It makes it hard when you want the set a date from the server-side.

**Comment by babakhani** [comment]
@hadimajidi i created another example that have `minDate` config at first, after that i update the value by using `setDate`, as you can see after this line 
`pd.setDate(new Date());` 
`minDate` config steel works fine, please create and example on jsfiddle, thanks.
