### ISSUE TITLE
setDate function bug

### ISSUE THREAD

**Issue by uxitten** [babakhani/pwt.datepicker#73]
آقای باباخانی ممنون از پلاگین که تهیه کرده اید
وقتی از متد setDate استفاده میکنیم خطای زیر ایجاد می شود

Uncaught TypeError: this.timePicker.setTime is not a function

![error](https://cloud.githubusercontent.com/assets/1549069/14072363/ba43d8c2-f4d0-11e5-9c58-ca2483605d64.png)

**Comment by babakhani** [comment]
این مورد رو بزودی بررسی می کنم و تو نسخه جدید اصلاح خواهد شد
با سپاس از گزارش شما

**Comment by faridv** [comment]
سلام
من هم دقیقاً همین مشکل رو دارم و با وجود تمام ویژگی‌های مثبت این پلاگین نمی‌تونم به خاطر این مشکل ازش استفاده کنم.
میشه خواهش کنم برطرف کردن این ایراد رو تو اولویت بذارید؟ :pray:

**Comment by uxitten** [comment]
سلام اقا فريد فعلا از روش 
Try catch 
استفاده كنيد تا ادامه فرايند جاوااسكريپت به مشكل نخورد  من هم از اين روش استفاده كردم تا اين باگ درست بشه

**Comment by mohsen** [comment]
+1

**Comment by yeganehaym** [comment]
+1

**Comment by navid-dada** [comment]
+1

**Comment by babakhani** [comment]
New version is under development.
this bug fixed in new version.
you can see last document and examples in this link:
[http://babakhani.github.io/PersianWebToolkit/beta/datepicker/](http://babakhani.github.io/PersianWebToolkit/beta/datepicker/)
also you can use last beta version by 
`npm i persian-datepicker@beta`
